@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

EduDex *-right-> "1" UniquePersonList
EduDex *-right-> "1" UniqueTagList
EduDex *-down-> "1" UniqueSubjectList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniquePersonList

UniqueTagList -right-> "*" Tag
UniquePersonList -right-> Person

Person -up-> "0...*" Tag

Person *--> Name
Person *--> Phone
Person *--> School
Person *--> Address
Person *--> "    0...*" Lesson

Lesson *--> "1" Subject
Lesson *--> "1  " Day
' A Lesson has two Time objects (start and end)
Lesson *--> "2" Time

UniqueSubjectList -right-> Subject
@enduml
