@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "EduDex Storage" #F4F6F6{
Class "<<interface>>\nEduDexStorage" as EduDexStorage
Class JsonEduDexStorage
Class JsonSerializableEduDex
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" EduDexStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> EduDexStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonEduDexStorage .up.|> EduDexStorage
JsonEduDexStorage ..> JsonSerializableEduDex
JsonSerializableEduDex --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

@enduml
